/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package fr.smile.socialnetworking.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fr.smile.socialnetworking.model.MeetupsRegistration;
import fr.smile.socialnetworking.service.MeetupsRegistrationLocalServiceUtil;

/**
 * The extended model base implementation for the MeetupsRegistration service. Represents a row in the &quot;SN_SMILE_MeetupsRegistration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MeetupsRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MeetupsRegistrationImpl
 * @see fr.smile.socialnetworking.model.MeetupsRegistration
 * @generated
 */
public abstract class MeetupsRegistrationBaseImpl
	extends MeetupsRegistrationModelImpl implements MeetupsRegistration {
	public void persist() throws SystemException {
		MeetupsRegistrationLocalServiceUtil.updateMeetupsRegistration(this);
	}
}